### ISSUE TITLE
Error with password encoding

### ISSUE THREAD

**Issue by rogersa2k** [ngosang/urbackup-exporter#3]
I tried on a couple different boxes:

urbackup-exporter  | 2023-01-11 10:30:26 INFO     Starting UrBackup Prometheus Exporter ...
urbackup-exporter  | Traceback (most recent call last):
urbackup-exporter  |   File "/urbackup-exporter.py", line 185, in <module>
urbackup-exporter  |     prometheus_client.core.REGISTRY.register(UrBackupCollector(
urbackup-exporter  |                                              ^^^^^^^^^^^^^^^^^^
urbackup-exporter  |   File "/urbackup-exporter.py", line 22, in __init__
urbackup-exporter  |     self.get_status_autologin()
urbackup-exporter  |   File "/urbackup-exporter.py", line 134, in get_status_autologin
urbackup-exporter  |     api_status = self.api.get_status()
urbackup-exporter  |                  ^^^^^^^^^^^^^^^^^^^^^
urbackup-exporter  |   File "/usr/local/lib/python3.11/site-packages/urbackup_api/__init__.py", line 336, in get_status
urbackup-exporter  |     if not self.login():
urbackup-exporter  |            ^^^^^^^^^^^^
urbackup-exporter  |   File "/usr/local/lib/python3.11/site-packages/urbackup_api/__init__.py", line 128, in login
urbackup-exporter  |     login = self._get_json("login", {});
urbackup-exporter  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
urbackup-exporter  |   File "/usr/local/lib/python3.11/site-packages/urbackup_api/__init__.py", line 104, in _get_json
urbackup-exporter  |     return json.loads(data.decode("utf-8","ignore"))
urbackup-exporter  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urbackup-exporter  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
urbackup-exporter  |     return _default_decoder.decode(s)
urbackup-exporter  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
urbackup-exporter  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
urbackup-exporter  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
urbackup-exporter  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urbackup-exporter  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
urbackup-exporter  |     raise JSONDecodeError("Expecting value", s, err.value) from None
urbackup-exporter  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
urbackup-exporter exited with code 1

**Comment by rogersa2k** [comment]
And via the Python script:

pip install -r requirements.txt
...

export URBACKUP_SERVER_URL=http://192.168.1.87:55414/

python urbackup-exporter.py

2023-01-11 10:34:49 INFO     Starting UrBackup Prometheus Exporter ...
Traceback (most recent call last):
  File "/home/arogers/Documents/GitHub/urbackup-exporter/urbackup-exporter.py", line 185, in <module>
    prometheus_client.core.REGISTRY.register(UrBackupCollector(
  File "/home/arogers/Documents/GitHub/urbackup-exporter/urbackup-exporter.py", line 22, in __init__
    self.get_status_autologin()
  File "/home/arogers/Documents/GitHub/urbackup-exporter/urbackup-exporter.py", line 134, in get_status_autologin
    api_status = self.api.get_status()
  File "/home/arogers/.local/lib/python3.10/site-packages/urbackup_api/__init__.py", line 336, in get_status
    if not self.login():
  File "/home/arogers/.local/lib/python3.10/site-packages/urbackup_api/__init__.py", line 128, in login
    login = self._get_json("login", {});
  File "/home/arogers/.local/lib/python3.10/site-packages/urbackup_api/__init__.py", line 104, in _get_json
    return json.loads(data.decode("utf-8","ignore"))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rogersa2k** [comment]
Aha, I figured it out... I have an ! in my password and the script cannot handle that. :|

Once I escaped it the script is fine but that didn't fix the Docker version. I'll change my password to something without such a special character. :)

**Comment by ngosang** [comment]
You can open a pr to fix the issue if you want to.

**Comment by DustyArmstrong** [comment]
Am having the same issue but changing the password not to include special characters still doesn't fix the issue on the Docker container, unless I'm doing something wrong.

**Comment by DustyArmstrong** [comment]
The suggested fix is to use single quotes `' '` due to the way Linux handles environment variables. This would disable string substitution. I can do a PR but I'm of course not that familiar with the project.

**Comment by renemarc** [comment]
I was stumbling on the same issue, turns out to be user error. Forgetting to include the easily-forgettable `/x` API path to the UrBackup server means that the JSON decoder will be ingesting non-JSON content. Ideally the urbackup-server-web-api-wrapper package should implement a defensive format verification, alas that package seems to be stale.

So, do make sure that you provide:
`URBACKUP_SERVER_URL=http://192.168.1.87:55414/x`

not:
`URBACKUP_SERVER_URL=http://192.168.1.87:55414/`
